# Generated by Django 4.1 on 2023-03-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0003_college"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("courseName", models.CharField(max_length=50)),
                ("courseDescription", models.CharField(max_length=100)),
                ("courseDuration", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "ORS_COURSE",
            },
        ),
    ]
