# Generated by Django 4.1 on 2023-03-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0004_course"),
    ]

    operations = [
        migrations.CreateModel(
            name="Marksheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rollNumber", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=50)),
                ("physics", models.IntegerField()),
                ("chemistry", models.IntegerField()),
                ("maths", models.IntegerField()),
            ],
            options={
                "db_table": "ORS_MARKSHEET",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstName", models.CharField(max_length=50)),
                ("lastName", models.CharField(max_length=50)),
                ("dob", models.DateField(max_length=20)),
                ("mobileNumber", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("college_ID", models.IntegerField()),
                ("collegeName", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "ORS_STUDENT",
            },
        ),
    ]
