# Generated by Django 4.1 on 2023-03-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0005_marksheet_student"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("SubjectName", models.CharField(max_length=50)),
                ("SubjectDescription", models.CharField(max_length=50)),
                ("Course_ID", models.IntegerField()),
                ("courseName", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "ORS_SUBJECT",
            },
        ),
    ]
