# Generated by Django 4.1 on 2023-03-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0007_faculty"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("examTime", models.CharField(max_length=40)),
                ("examDate", models.DateField()),
                ("subject_ID", models.IntegerField()),
                ("subjectName", models.CharField(max_length=50)),
                ("course_ID", models.IntegerField()),
                ("courseName", models.CharField(max_length=50)),
                ("semester", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "ORS_TIMETABLE",
            },
        ),
    ]
