# Generated by Django 4.1 on 2023-05-18 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0008_timetable"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="subject",
            table="SUBJECT_ORS",
        ),
    ]
