# Generated by Django 4.1 on 2023-05-18 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0009_alter_subject_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="subject",
            table="ORS_SUBJECT",
        ),
    ]
